name: Sync to Vercel Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   # updated version

      - name: Push to Vercel repo
        env:
          TOKEN: ${{ secrets.VERCEL_REPO_TOKEN }}
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync-bot@example.com"

          git remote add vercel https://x-access-token:$TOKEN@github.com/edinle/mendingkidsdesign.git
          
          git push vercel main --force
